#!/usr/bin/env python3
"""Add the durable Frontier Loop documentation shape without moving existing docs.

The default is a dry run. Applying is additive. --force-generated only replaces files that carry
this tool's marker (or JSON generated_by identity); source documents are never rewritten.
"""
from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

MD_MARKER = "<!-- GENERATED BY frontier-loop retrofit-agent-docs; preserve source docs -->"
JSON_GENERATOR = "frontier-loop/retrofit-agent-docs"
IGNORED_PARTS = {".git", ".agents", ".codex", ".opencode", "node_modules", "target", "dist", "build"}

CATEGORIES: dict[str, tuple[str, ...]] = {
    "architecture": ("architecture", "design", "system", "component", "module"),
    "glossary": ("glossary", "domain", "vocabulary", "terminology"),
    "authority": ("authority", "security", "permission", "approval", "access", "threat"),
    "testing": ("test", "qa", "validation", "verification", "quality"),
    "operations": ("runbook", "operation", "process", "deployment", "runtime", "production"),
    "failures": ("incident", "failure", "postmortem", "bug", "recovery"),
    "decisions": ("adr", "decision", "rfc"),
    "tickets": ("ticket", "plan", "roadmap", "backlog"),
    "evidence": ("evidence", "benchmark", "result", "report"),
}


@dataclass(frozen=True)
class Source:
    path: str
    categories: tuple[str, ...]


def classify(path: Path, docs: Path) -> tuple[str, ...]:
    relative = path.relative_to(docs).as_posix().lower()
    haystack = re.sub(r"[-_.]+", " ", relative)
    return tuple(category for category, words in CATEGORIES.items() if any(word in haystack for word in words))


def discover_sources(docs: Path) -> list[Source]:
    if not docs.exists():
        return []
    sources: list[Source] = []
    for path in sorted(docs.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(docs)
        if set(relative.parts) & IGNORED_PARTS or relative.parts[:1] == ("agent",):
            continue
        categories = classify(path, docs)
        if categories:
            sources.append(Source(relative.as_posix(), categories))
    return sources


def source_lines(sources: list[Source], category: str) -> str:
    matching = [source for source in sources if category in source.categories]
    if not matching:
        return "- `UNRESOLVED` — no source document was classified automatically; review the docs tree manually."
    return "\n".join(f"- [`{source.path}`](../{source.path})" for source in matching)


def templates(sources: list[Source]) -> dict[str, str]:
    return {
        "README.md": """# Agent Documentation

This directory is durable, versioned repository memory for agentic work. Chat history can provide context, but it is not execution authority.

## Canonical files

- `PROJECT_MAP.md` — low-resolution product and component map.
- `DOMAIN_GLOSSARY.md` — domain terms with authoritative sources.
- `AUTHORITY_MAP.md` — who may propose, validate, approve, and apply consequential actions.
- `TEST_TOPOLOGY.md` — test families, commands, ownership, and locked megafiles.
- `PROCESS_POLICY.md` — command/process ownership and cleanup rules.
- `FAILURE_CATALOG.md` — recurring failures and regression evidence.
- `CURRENT_FRONTIER.json` — generated cross-track execution snapshot.
- `architecture-baseline.json` — reviewed architecture ratchet baseline.
- `SOURCE_INDEX.md` — source-document classification created during retrofit.

Unknowns remain explicitly `UNRESOLVED`; this scaffold does not invent project facts.
""",
        "PROJECT_MAP.md": f"""# Project Map

## Purpose and destination

`UNRESOLVED` — identify the authoritative product description.

## Major components and seams

`UNRESOLVED` — map stable components, entry points, public interfaces, and owned data.

## Likely source documents

{source_lines(sources, 'architecture')}

## Current execution tracks

`UNRESOLVED` — link active `docs/tickets/<track>/master-plan.md` files.
""",
        "DOMAIN_GLOSSARY.md": f"""# Domain Glossary

| Term | Definition | Authoritative source | Status |
|---|---|---|---|

Do not add a definition without a source or an explicit human decision.

## Likely source documents

{source_lines(sources, 'glossary')}
""",
        "AUTHORITY_MAP.md": f"""# Authority Map

## Human gates

`UNRESOLVED` — enumerate actions that require explicit human approval.

| Action or transition | Proposer | Validator | Approver | Applier | Durable evidence |
|---|---|---|---|---|---|

## Ordering invariants

`UNRESOLVED` — record rules such as validate-before-persist and approve-before-apply only when sources support them.

## Likely source documents

{source_lines(sources, 'authority')}
""",
        "TEST_TOPOLOGY.md": f"""# Test Topology

## Test families and commands

`UNRESOLVED` — record L0 through L4 verification commands and their expected cost.

## Locked files

| Path | Baseline LOC | Allowed growth | Split direction | Source/evidence |
|---|---:|---:|---|---|

## Fixture and harness ownership

`UNRESOLVED` — distinguish declarative scenarios from reusable environment drivers.

## Likely source documents

{source_lines(sources, 'testing')}
""",
        "PROCESS_POLICY.md": f"""# Process Policy

Every spawned command must have an owner lease. Ticket, agent, and coordinator completion require zero live owned descendants and zero open leases.

## Project-specific commands and services

`UNRESOLVED` — list commands that can spawn servers, browsers, native tools, MCP processes, containers, or grandchildren.

## Resource limits

`UNRESOLVED` — define timeout, PID, CPU, memory, and disk limits for stress or long-running work.

## Likely source documents

{source_lines(sources, 'operations')}
""",
        "FAILURE_CATALOG.md": f"""# Failure Catalog

| ID | Symptom | Root cause | Detection | Safe repair | Regression evidence |
|---|---|---|---|---|---|

## Likely source documents

{source_lines(sources, 'failures')}
""",
        "SOURCE_INDEX.md": "# Source Index\n\n" + (
            "\n".join(
                f"- [`{source.path}`](../{source.path}) — {', '.join(source.categories)}" for source in sources
            )
            if sources
            else "- No source documents were classified automatically."
        ) + "\n",
    }


def generated_markdown(path: Path) -> bool:
    if not path.exists():
        return False
    return MD_MARKER in path.read_text(encoding="utf-8", errors="replace")[:300]


def generated_json(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return False
    return isinstance(value, dict) and value.get("generated_by") == JSON_GENERATOR


def write_markdown(path: Path, body: str, *, apply: bool, force: bool, actions: list[str]) -> None:
    if path.exists() and not (force and generated_markdown(path)):
        actions.append(f"PRESERVE {path}")
        return
    actions.append(("REFRESH " if path.exists() else "CREATE ") + str(path))
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(MD_MARKER + "\n" + body.rstrip() + "\n", encoding="utf-8")


def write_json(path: Path, value: dict[str, Any], *, apply: bool, force: bool, actions: list[str]) -> None:
    if path.exists() and not (force and generated_json(path)):
        actions.append(f"PRESERVE {path}")
        return
    actions.append(("REFRESH " if path.exists() else "CREATE ") + str(path))
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(value, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("docs", type=Path, help="Existing docs directory or intended docs path")
    parser.add_argument("--apply", action="store_true", help="Apply additive changes; default is dry-run")
    parser.add_argument("--force-generated", action="store_true", help="Refresh only files previously generated by this tool")
    args = parser.parse_args()

    docs = args.docs.expanduser().resolve()
    if docs.exists() and not docs.is_dir():
        raise SystemExit(f"not a directory: {docs}")
    sources = discover_sources(docs)
    agent = docs / "agent"
    actions: list[str] = []

    for name, body in templates(sources).items():
        write_markdown(agent / name, body, apply=args.apply, force=args.force_generated, actions=actions)

    directory_descriptions = {
        "decisions": "Canonical decisions or pointers to existing ADR/RFC locations. Supersede decisions explicitly; do not rewrite history.",
        "evidence": "Append-only cross-ticket evidence indexes. Ticket-specific attempts remain under their ticket directories.",
        "wayfinding": "Destination maps, decision frontiers, research, and prototypes for ambiguous efforts.",
        "migrations": "Additive migration records for documentation and ticket-shape changes.",
    }
    for name, description in directory_descriptions.items():
        actions.append(f"ENSURE {agent / name}/")
        write_markdown(
            agent / name / "README.md",
            f"# {name.title()}\n\n{description}\n",
            apply=args.apply,
            force=args.force_generated,
            actions=actions,
        )

    write_json(
        agent / "CURRENT_FRONTIER.json",
        {
            "schema_version": 1,
            "generated_by": JSON_GENERATOR,
            "generated_at": None,
            "tracks": [],
            "note": "Populate from reviewed track frontiers; chat state is not canonical.",
        },
        apply=args.apply,
        force=args.force_generated,
        actions=actions,
    )
    write_json(
        agent / "architecture-baseline.json",
        {
            "schema_version": 1,
            "generated_by": JSON_GENERATOR,
            "generated_at": None,
            "files": {},
            "notes": ["Populate only through a reviewed deterministic scan."],
        },
        apply=args.apply,
        force=args.force_generated,
        actions=actions,
    )

    write_markdown(
        docs / "tickets" / "README.md",
        """# Ticket Tracks

Each execution track uses:

```text
<track>/
  master-plan.md
  track.yaml
  frontier.json
  current-sprint.md
  policies/
  NNN-<slug>/
    ticket.md
    contract.yaml
    validation.md
    evidence/
```

Run `wayfinder` to recover or capture planning, then `execute-frontier` continuously from local files. The current conversation remains the coordinator; no external issue tracker, webhook, or event watcher is required.
""",
        apply=args.apply,
        force=args.force_generated,
        actions=actions,
    )

    migration_body = "\n".join(
        [
            "# Documentation Retrofit Migration Map",
            "",
            f"Date: {date.today().isoformat()}",
            "",
            "No source document was moved or rewritten. Canonical files contain pointers and explicit unresolved sections only.",
            "",
            "## Classified source documents",
            "",
            *(
                [f"- `{source.path}` — {', '.join(source.categories)}" for source in sources]
                or ["- None detected automatically."]
            ),
            "",
            "## Planned or applied actions",
            "",
            *[f"- {action}" for action in actions],
        ]
    )
    write_markdown(
        agent / "migrations" / f"{date.today().isoformat()}-docs-retrofit.md",
        migration_body,
        apply=args.apply,
        force=args.force_generated,
        actions=actions,
    )

    print(
        json.dumps(
            {
                "docs": str(docs),
                "apply": args.apply,
                "force_generated": args.force_generated,
                "classified_sources": [
                    {"path": source.path, "categories": list(source.categories)} for source in sources
                ],
                "actions": actions,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
