[package]
name = "workspace-template-native"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "workspace-template"
path = "src/main.rs"

[dependencies]
hex.workspace = true
libc.workspace = true
glob.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
toml.workspace = true
windows-sys.workspace = true
