#!/usr/bin/env python3
"""Add Frontier Loop contracts and policies to an existing local ticket track.

The migration is additive by default. Existing ticket, validation, and generated files are
preserved unless --force-generated is supplied and the target carries this tool's marker.
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any, Iterable

import _mini_yaml as yaml

MD_MARKER = "<!-- GENERATED BY frontier-loop retrofit-ticket-pack; source tickets are preserved -->"
YAML_MARKER = "# GENERATED BY frontier-loop retrofit-ticket-pack; source tickets are preserved"
GENERATED_MARKERS = (MD_MARKER, YAML_MARKER)
JSON_GENERATOR = "frontier-loop retrofit-ticket-pack"
DONE = {"committed", "closed", "superseded"}
IGNORED_PARTS = {".git", ".agents", ".codex", ".opencode", "node_modules", "target", "dist", "build", "evidence"}


@dataclass
class TicketSource:
    directory: Path
    ticket_path: Path
    validation_path: Path | None
    text: str
    source_id: str
    title: str
    canonical_id: str = ""
    sections: dict[str, str] = field(default_factory=dict)
    dependency_text: str = ""
    kind: str = "implementation"
    status: str = "ready"
    status_reason: str = "no authoritative completion marker found"


def normalize_heading(value: str) -> str:
    value = re.sub(r"[`*_]", "", value).strip().lower()
    value = re.sub(r"\s+", " ", value)
    return value


def parse_sections(text: str) -> dict[str, str]:
    matches = list(re.finditer(r"^##\s+(.+?)\s*$", text, re.MULTILINE))
    result: dict[str, str] = {}
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        result[normalize_heading(match.group(1))] = text[start:end].strip()
    return result


def section_values(sections: dict[str, str], names: Iterable[str], *, prefix: bool = True) -> list[str]:
    wanted = [normalize_heading(name) for name in names]
    values: list[str] = []
    for heading, content in sections.items():
        if any(heading == name or (prefix and heading.startswith(name)) for name in wanted):
            values.append(content)
    return values


def section_text(sections: dict[str, str], names: Iterable[str], *, prefix: bool = True) -> str:
    return "\n\n".join(value for value in section_values(sections, names, prefix=prefix) if value).strip()


def bullets(block: str) -> list[str]:
    values: list[str] = []
    for line in block.splitlines():
        match = re.match(r"\s*[-*+]\s+(?:\[[ xX]\]\s*)?(.*\S)\s*$", line)
        if match:
            value = match.group(1).strip()
            if value and value not in values:
                values.append(value)
    return values


def first_prose(block: str) -> str:
    for paragraph in re.split(r"\n\s*\n", block.strip()):
        value = " ".join(line.strip() for line in paragraph.splitlines()).strip()
        value = re.sub(r"^[-*+]\s+", "", value)
        if value and not value.startswith("```"):
            return value
    return ""


def parse_header(text: str, folder: Path) -> tuple[str, str]:
    header = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
    if header:
        raw = header.group(1).strip()
        match = re.match(r"Ticket\s+(.+?)\s+(?:—|–|-)\s+(.+)$", raw, re.IGNORECASE)
        if not match:
            match = re.match(r"Ticket\s+([^:]+?)\s*:\s*(.+)$", raw, re.IGNORECASE)
        if match:
            return match.group(1).strip(), match.group(2).strip()
        match = re.match(r"Ticket\s+([^\s]+)\s*$", raw, re.IGNORECASE)
        if match:
            return match.group(1).strip(), folder.name

    # Safe fallback: capture a numeric ticket plus optional single-letter hierarchy only.
    match = re.match(r"^(\d+[A-Za-z]?(?:-[A-Za-z])*)(?:[-_]|$)", folder.name)
    if match:
        source_id = match.group(1)
        title = folder.name[match.end() :].lstrip("-_ ") or folder.name
        return source_id, title.replace("-", " ").strip().title()
    return folder.name, folder.name.replace("-", " ").title()


def infer_status(text: str) -> tuple[str, str]:
    explicit = re.search(r"^Status\s*:\s*([^\n]+)", text, re.IGNORECASE | re.MULTILINE)
    if explicit:
        value = explicit.group(1).strip().lower()
        if any(word in value for word in ("closed", "complete", "completed", "done", "validated")):
            return "closed", f"explicit status: {explicit.group(1).strip()}"
        if any(word in value for word in ("blocked", "hold", "waiting")):
            return "blocked", f"explicit status: {explicit.group(1).strip()}"
        if any(word in value for word in ("active", "progress", "implement")):
            return "ready", f"explicit status retained as executable: {explicit.group(1).strip()}"

    lowered = text.lower()
    closed_phrases = (
        "this ticket is closed",
        "tracking ticket is closed",
        "ticket is complete",
        "ticket is completed",
        "implementation and fresh independent review complete",
        "implementation and independent review complete",
    )
    if any(phrase in lowered for phrase in closed_phrases):
        return "closed", "explicit completion phrase in source ticket"

    boxes = re.findall(r"^\s*[-*+]\s+\[([ xX])\]", text, re.MULTILINE)
    if boxes and all(value.lower() == "x" for value in boxes) and re.search(r"\b(?:closed|complete|completed|validated)\b", lowered):
        return "closed", "all source checkboxes are checked and completion is stated"
    if re.search(r"\b(?:blocked|on hold|waiting for)\b", lowered) and not re.search(r"\bunblocked\b", lowered):
        return "blocked", "blocking language found; review manually"
    return "ready", "no authoritative completion marker found"


def infer_kind(text: str) -> str:
    lowered = text.lower()
    if "tracking parent" in lowered or "tracking ticket" in lowered or "this parent validation" in lowered:
        return "tracker"
    return "implementation"


def risk_lane(title: str, text: str) -> tuple[int, list[str]]:
    sample = f"{title}\n{text}".lower()
    reasons: list[str] = []
    lane3 = {
        "production apply": "production apply authority",
        "authority boundary": "authority boundary",
        "apply authority": "apply authority",
        "approval authority": "approval authority",
        "execution authority": "execution authority",
        "funds": "funds/capital",
        "capital": "funds/capital",
        "kill switch": "kill switch",
        "destructive": "destructive effect",
        "credential": "credential handling",
        "security boundary": "security boundary",
        "process lifecycle": "process ownership",
        "process tree": "process ownership",
        "transaction admission": "transaction admission",
        "mutation admission": "mutation admission",
        "release gate": "release authority",
        "live adapter": "live external effect",
    }
    lane2 = {
        "event stream": "event stream",
        "persistence": "persistence",
        "migration": "migration",
        "protocol": "protocol",
        "integration": "integration",
        "concurrency": "concurrency",
        "recovery": "recovery",
        "reconnect": "reconnect",
        "scheduler": "scheduler",
        "native": "native boundary",
        "transaction": "transaction semantics",
        "database": "database",
        "nats": "messaging",
        "mcp": "MCP/process boundary",
    }
    lane0 = ("documentation", "readme", "typo", "rename only", "generated index", "format only")
    for needle, reason in lane3.items():
        if needle in sample and reason not in reasons:
            reasons.append(reason)
    if reasons:
        return 3, reasons
    for needle, reason in lane2.items():
        if needle in sample and reason not in reasons:
            reasons.append(reason)
    if reasons:
        return 2, reasons
    if any(needle in sample for needle in lane0):
        return 0, ["mechanical/documentation language"]
    return 1, ["bounded local behavior by default"]


def review_lenses(lane: int) -> list[str]:
    if lane == 0:
        return ["combined"]
    if lane in (1, 2):
        return ["spec-authority", "code-test"]
    return ["spec-authority", "code-test", "operations-security"]


def extract_commands(validation: Path | None) -> list[str]:
    if validation is None:
        return []
    text = validation.read_text(encoding="utf-8", errors="replace")
    commands: list[str] = []
    for block in re.findall(r"```(?:[\w.+-]+)?\s*\n(.*?)```", text, re.DOTALL):
        for line in block.splitlines():
            value = line.strip()
            if not value or value.startswith("#"):
                continue
            if value not in commands:
                commands.append(value)
    return commands


def extract_human_gates(text: str) -> list[str]:
    keywords = ("operator confirmation", "human approval", "manual approval", "user approval", "explicit approval")
    values: list[str] = []
    for line in text.splitlines():
        lowered = line.lower()
        if any(keyword in lowered for keyword in keywords):
            value = re.sub(r"^\s*[-*+]\s+", "", line).strip()
            if value and value not in values:
                values.append(value)
    return values


def marker_for(path: Path) -> str:
    if path.suffix.lower() in {".yaml", ".yml"}:
        return YAML_MARKER
    return MD_MARKER


def generated_file(path: Path) -> bool:
    if not path.exists():
        return False
    prefix = path.read_text(encoding="utf-8", errors="replace")[:300]
    return any(marker in prefix for marker in GENERATED_MARKERS)


def write_generated(path: Path, text: str, *, apply: bool, force: bool, actions: list[str]) -> None:
    if path.exists() and not (force and generated_file(path)):
        actions.append(f"PRESERVE {path}")
        return
    actions.append(f"WRITE {path}")
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"{marker_for(path)}\n{text.rstrip()}\n", encoding="utf-8")


def generated_json_file(path: Path) -> bool:
    if not path.exists():
        return False
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    return isinstance(data, dict) and data.get("generated_by") == JSON_GENERATOR


def write_generated_json(
    path: Path,
    data: dict[str, Any],
    *,
    apply: bool,
    force: bool,
    actions: list[str],
) -> None:
    if path.exists() and not (force and generated_json_file(path)):
        actions.append(f"PRESERVE {path}")
        return
    actions.append(f"WRITE {path}")
    if apply:
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {"generated_by": JSON_GENERATOR, **data}
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def discover_tickets(track: Path) -> list[TicketSource]:
    sources: list[TicketSource] = []
    for ticket_path in sorted(track.rglob("ticket.md")):
        relative_parts = set(ticket_path.relative_to(track).parts[:-1])
        if relative_parts & IGNORED_PARTS:
            continue
        directory = ticket_path.parent
        text = ticket_path.read_text(encoding="utf-8", errors="replace")
        source_id, title = parse_header(text, directory)
        validation = next((path for path in (directory / "validation.md", directory / "verification.md") if path.exists()), None)
        status, status_reason = infer_status(text)
        sections = parse_sections(text)
        dependency_text = section_text(sections, ("depends on", "dependencies", "blocked by"))
        sources.append(
            TicketSource(
                directory=directory,
                ticket_path=ticket_path,
                validation_path=validation,
                text=text,
                source_id=source_id,
                title=title,
                sections=sections,
                dependency_text=dependency_text,
                kind=infer_kind(text),
                status=status,
                status_reason=status_reason,
            )
        )
    return sources


def normalize_execution_state(state: str) -> str | None:
    value = state.strip().lower().replace("-", "_")
    if value in {"committed", "closed", "superseded", "cancelled"}:
        return value
    if value in {"passed", "review_passed", "validation_passed"}:
        return "passed"
    if value.startswith("review") or value in {"reviewer_started", "reviewer_complete"}:
        return "review"
    if value.startswith("repair") or value in {"fix_started", "fix_complete"}:
        return "repair"
    if value in {
        "started", "claimed", "executor_started", "executor_complete",
        "implementation_started", "implementation_complete", "in_progress",
    }:
        return "in_progress"
    if value in {"blocked", "failed", "validation_failed", "review_failed"}:
        return "blocked"
    return None


def load_execution_state(track: Path) -> dict[str, tuple[str, str]]:
    """Read latest ticket states from retained JSONL journals when present."""
    latest: dict[str, tuple[tuple[int, str, int], str, str]] = {}
    candidates = [
        path for path in sorted(track.glob("*execution-state*.jsonl"))
        if "example" not in path.name.lower()
    ]
    for path in candidates:
        for line_number, raw in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
            if not raw.strip():
                continue
            try:
                event = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if not isinstance(event, dict):
                continue
            ticket = str(event.get("ticket_id", "")).strip()
            state_raw = str(event.get("state", "")).strip()
            normalized = normalize_execution_state(state_raw)
            if not ticket or normalized is None:
                continue
            try:
                sequence = int(event.get("sequence", line_number))
            except (TypeError, ValueError):
                sequence = line_number
            timestamp = str(event.get("timestamp", ""))
            key = (sequence, timestamp, line_number)
            reason = f"{path.name} event {state_raw!r} sequence {sequence}"
            prior = latest.get(ticket.casefold())
            if prior is None or key > prior[0]:
                latest[ticket.casefold()] = (key, normalized, reason)
    return {ticket: (status, reason) for ticket, (_, status, reason) in latest.items()}


def load_status_overrides(path: Path | None) -> dict[str, str]:
    if path is None:
        return {}
    if not path.exists():
        raise SystemExit(f"status override file does not exist: {path}")
    raw = path.read_text(encoding="utf-8")
    data = json.loads(raw) if path.suffix.lower() == ".json" else yaml.safe_load(raw)
    if isinstance(data, dict) and isinstance(data.get("statuses"), dict):
        data = data["statuses"]
    if not isinstance(data, dict):
        raise SystemExit("status override file must be a mapping or contain a 'statuses' mapping")
    result: dict[str, str] = {}
    allowed = DONE | {"planned", "ready", "blocked", "cancelled", "claimed", "in_progress", "review", "repair", "passed"}
    for key, value in data.items():
        status = str(value).strip().lower()
        if status not in allowed:
            raise SystemExit(f"unsupported status override {value!r} for {key}")
        result[str(key).strip().casefold()] = status
    return result


def resolve_source(token: str, alias_map: dict[str, str], sources: list[TicketSource]) -> TicketSource | None:
    candidates = [token, Path(token).name]
    canonical = None
    for candidate in candidates:
        canonical = alias_map.get(candidate.casefold())
        if canonical:
            break
    if canonical is None:
        direct = [s for s in sources if s.canonical_id.casefold() == token.casefold()]
        return direct[0] if len(direct) == 1 else None
    return next((source for source in sources if source.canonical_id == canonical), None)


def apply_status_evidence(
    *,
    track: Path,
    sources: list[TicketSource],
    alias_map: dict[str, str],
    current_ticket: str | None,
    current_status: str,
    trust_current_dependencies: bool,
    status_overrides_path: Path | None,
    warnings: list[str],
) -> str | None:
    """Apply journal, explicit current-position, and operator override evidence."""
    by_id = {source.canonical_id: source for source in sources}
    journal = load_execution_state(track)
    for token, (status, reason) in journal.items():
        source = resolve_source(token, alias_map, sources)
        if source is None:
            warnings.append(f"execution-state ticket {token!r} did not resolve to a discovered ticket")
            continue
        source.status = status
        source.status_reason = reason

    overrides = load_status_overrides(status_overrides_path)
    for token, status in overrides.items():
        source = resolve_source(token, alias_map, sources)
        if source is None:
            warnings.append(f"status override ticket {token!r} did not resolve to a discovered ticket")
            continue
        source.status = status
        source.status_reason = f"explicit status override from {status_overrides_path.name}"

    resolved_current: TicketSource | None = None
    if current_ticket:
        resolved_current = resolve_source(current_ticket, alias_map, sources)
        if resolved_current is None:
            warnings.append(f"explicit current ticket {current_ticket!r} did not resolve")
        else:
            resolved_current.status = current_status
            resolved_current.status_reason = f"explicit --current-ticket {current_ticket!r}"

    if trust_current_dependencies and resolved_current is None:
        warnings.append("--trust-current-dependencies was ignored because --current-ticket did not resolve")
    elif trust_current_dependencies and resolved_current is not None:
        # Resolve the dependency graph using source prose before contracts are written.
        graph: dict[str, list[str]] = {}
        for source in sources:
            graph[source.canonical_id] = resolve_dependencies(source, alias_map, sources)[0]
        stack = list(graph.get(resolved_current.canonical_id, []))
        visited: set[str] = set()
        while stack:
            ticket_id = stack.pop()
            if ticket_id in visited:
                continue
            visited.add(ticket_id)
            dependency = by_id.get(ticket_id)
            if dependency is None:
                continue
            if dependency.status not in DONE:
                dependency.status = "closed"
                dependency.status_reason = f"explicit trust of transitive dependencies for current ticket {resolved_current.canonical_id}"
            stack.extend(graph.get(ticket_id, []))
        warnings.append(
            f"operator assertion marked {len(visited)} transitive dependencies of {resolved_current.canonical_id} closed; review before autonomous execution"
        )

    if resolved_current is None:
        active_statuses = {"claimed", "in_progress", "review", "repair", "passed"}
        active_sources = [source for source in sources if source.status in active_statuses]
        if len(active_sources) == 1:
            resolved_current = active_sources[0]
        elif len(active_sources) > 1:
            warnings.append(
                "multiple active tickets were inferred from retained status evidence; "
                "track.current_ticket remains unset until --current-ticket resolves the coordinator position"
            )
    return resolved_current.canonical_id if resolved_current else None


def code_aliases(source: TicketSource, track: Path) -> set[str]:
    aliases = {source.source_id, source.directory.name, source.ticket_path.parent.relative_to(track).as_posix()}
    parts = source.source_id.split("-")
    if len(parts) >= 3:
        for start in range(1, len(parts) - 1):
            aliases.add("-".join(parts[start:]))
    aliases.update(re.findall(r"\b[A-Z][A-Z0-9]*(?:-[A-Z0-9]+){2,}\b", source.title))
    return {alias.strip() for alias in aliases if alias.strip()}


def build_alias_map(sources: list[TicketSource], track: Path) -> dict[str, str]:
    candidates: dict[str, set[str]] = defaultdict(set)
    for source in sources:
        for alias in code_aliases(source, track):
            candidates[alias.casefold()].add(source.canonical_id)
    return {alias: next(iter(ids)) for alias, ids in candidates.items() if len(ids) == 1}


def dependency_candidates(block: str) -> list[str]:
    candidates: list[str] = []
    patterns = (
        r"\bTicket\s+([A-Za-z0-9][A-Za-z0-9._-]*)",
        r"`([A-Za-z0-9][A-Za-z0-9._-]*)`",
        r"\b(\d{3}[A-Za-z]?(?:-[A-Za-z0-9]+)*)\b",
        r"\b([A-Z][A-Z0-9]*(?:-[A-Z0-9]+){2,})\b",
        r"\b([A-Z](?:-[A-Z0-9]+){1,})\b",
    )
    for pattern in patterns:
        for match in re.finditer(pattern, block, re.IGNORECASE if pattern.startswith(r"\bTicket") else 0):
            value = match.group(1).strip().rstrip(".,;:")
            if value not in candidates:
                candidates.append(value)
    for target in re.findall(r"\]\(([^)]+/ticket\.md)\)", block, re.IGNORECASE):
        value = Path(target.replace("\\", "/")).parent.name
        if value and value not in candidates:
            candidates.append(value)
    return candidates


def looks_like_ticket_reference(token: str) -> bool:
    """Return whether an unresolved token is plausibly a ticket ID.

    Old validation prose frequently backticks state names such as ``review_failed``. Those
    must not be reported as unresolved dependencies merely because they appear in a
    Dependencies section.
    """
    return bool(
        re.search(r"\d", token)
        or re.fullmatch(r"[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)+", token)
        or token.casefold().startswith("ticket-")
    )


def resolve_dependencies(source: TicketSource, alias_map: dict[str, str], sources: list[TicketSource]) -> tuple[list[str], list[str]]:
    dependencies: list[str] = []
    unresolved: list[str] = []
    for token in dependency_candidates(source.dependency_text):
        resolved = alias_map.get(token.casefold())
        if resolved and resolved != source.canonical_id:
            if resolved not in dependencies:
                dependencies.append(resolved)
        elif (
            token.casefold() not in {source.source_id.casefold(), source.canonical_id.casefold()}
            and looks_like_ticket_reference(token)
        ):
            unresolved.append(token)

    # Tracking parents aggregate direct descendants even when the old prose listed children outside
    # a Dependencies heading. This is structural inference and is explicitly recorded as such.
    if source.kind == "tracker":
        prefix = source.source_id.casefold() + "-"
        descendants = [candidate for candidate in sources if candidate.source_id.casefold().startswith(prefix)]
        direct: list[TicketSource] = []
        for candidate in descendants:
            remainder = candidate.source_id[len(source.source_id) + 1 :]
            if "-" not in remainder:
                direct.append(candidate)
        for candidate in direct:
            if candidate.canonical_id != source.canonical_id and candidate.canonical_id not in dependencies:
                dependencies.append(candidate.canonical_id)
    return dependencies, unresolved


def make_ids(sources: list[TicketSource], flatten: bool, prefix: str) -> None:
    width = max(3, len(str(len(sources))))
    for index, source in enumerate(sources, start=1):
        source.canonical_id = f"{prefix}{index:0{width}d}" if flatten else source.source_id


def infer_parents(sources: list[TicketSource]) -> dict[str, str | None]:
    """Infer structural parents without encoding hierarchy into new IDs.

    Legacy ID prefixes are preferred because many existing packs use identifiers such as
    ``017-C-C-B-B``. Directory ancestry is a fallback for nested ticket layouts. Every
    inference remains visible in the generated contract and must be reviewed by a human.
    """
    parents: dict[str, str | None] = {}
    for source in sources:
        candidates: list[tuple[int, TicketSource]] = []
        source_folded = source.source_id.casefold()
        for candidate in sources:
            if candidate is source:
                continue
            candidate_folded = candidate.source_id.casefold()
            if source_folded.startswith(candidate_folded + "-"):
                candidates.append((10_000 + len(candidate_folded), candidate))
                continue
            try:
                relative = source.directory.relative_to(candidate.directory)
            except ValueError:
                continue
            if relative.parts:
                candidates.append((len(candidate.directory.parts), candidate))
        parents[source.canonical_id] = max(candidates, key=lambda item: item[0])[1].canonical_id if candidates else None
    return parents


def public_outcome(source: TicketSource) -> str:
    for names in (
        ("objective", "public outcome"),
        ("required behavior", "what to build"),
        ("acceptance criteria",),
    ):
        block = section_text(source.sections, names)
        values = bullets(block)
        if values:
            return values[0]
        prose = first_prose(block)
        if prose:
            return prose
    return f"Complete the observable behavior specified in {source.ticket_path.name} for {source.title}."


def contract_for(
    source: TicketSource,
    track: Path,
    dependencies: list[str],
    parent: str | None,
) -> dict[str, Any]:
    behavior_block = section_text(source.sections, ("required behavior", "what to build", "exact scope"))
    behaviors = bullets(behavior_block)
    invariants = bullets(section_text(source.sections, ("invariants", "locked decisions", "constraints")))
    out_of_scope = bullets(section_text(source.sections, ("out of scope", "non-goals", "non goals")))
    excluded = section_text(source.sections, ("out of scope", "non-goals", "non goals"))
    risk_source = source.text.replace(excluded, "") if excluded else source.text
    lane, lane_reasons = risk_lane(source.title, risk_source)
    status_reason = source.status_reason
    human_gates = extract_human_gates(source.text)
    relative_ticket = source.ticket_path.relative_to(track).as_posix()
    relative_validation = source.validation_path.relative_to(track).as_posix() if source.validation_path else None
    contract: dict[str, Any] = {
        "schema_version": 1,
        "id": source.canonical_id,
        "title": source.title,
        "legacy_ids": list(dict.fromkeys([source.source_id, source.directory.name])),
        "kind": source.kind,
        "execution_policy": "aggregate-only" if source.kind == "tracker" else "implement-and-review",
        "status": source.status,
        "parent": parent,
        "public_outcome": public_outcome(source),
        "behaviors": behaviors,
        "invariants": invariants,
        "out_of_scope": out_of_scope,
        "blocked_by": dependencies,
        "risk_lane": lane,
        "preflight_required": True,
        "read_set": [],
        "write_set": [],
        "conflict_keys": [f"unclassified:{source.canonical_id}"],
        "skills": ["test-topology"] if lane == 0 else ["tdd", "test-topology", "process-lifecycle"],
        "human_gates": human_gates,
        "stop_conditions": [
            "Stop before editing if the actual write set, conflict domain, persistence contract, or authority exceeds this inferred contract.",
            "Stop rather than inventing requirements where the preserved source ticket is ambiguous.",
        ],
        "commit_policy": "coordinator",
        "review_lenses": review_lenses(lane),
        "verification": {
            "red": [],
            "repair_levels": ["L0", "L1", "L2"],
            "landing_levels": ["L0", "L1", "L2"] + (["L3"] if lane == 2 else ["L3", "L4"] if lane == 3 else []),
            "commands": extract_commands(source.validation_path),
            "native_checks": [],
        },
        "budgets": {
            "locked_files": [],
            "max_new_test_file_loc": 800,
            "max_new_production_file_loc": 1000,
            "zero_owned_processes_after_run": True,
        },
        "retrofit": {
            "inferred": True,
            "source_ticket": relative_ticket,
            "source_validation": relative_validation,
            "status_reason": status_reason,
            "risk_reasons": lane_reasons,
            "dependency_source": source.dependency_text or None,
            "requires_human_review": True,
        },
    }
    return contract



def infer_docs_root(track: Path) -> Path | None:
    """Infer the repository docs directory from a conventional docs/tickets/<track> path."""
    for candidate in (track, *track.parents):
        if candidate.name == "tickets" and candidate.parent.name == "docs":
            return candidate.parent
    return None


def recovered_master_fields(source_master: Path | None) -> dict[str, Any]:
    if source_master is None or not source_master.exists():
        return {
            "goal": "UNRESOLVED — no source master plan was found.",
            "locked_decisions": [],
            "out_of_scope": [],
            "authority": [],
            "source": None,
        }
    raw = source_master.read_text(encoding="utf-8", errors="replace")
    sections = parse_sections(raw)
    goal_block = section_text(sections, ("goal", "objective", "purpose", "destination", "target state"))
    goal = first_prose(goal_block) or first_prose(re.sub(r"^#.*$", "", raw, count=1, flags=re.MULTILINE))
    locked = bullets(section_text(sections, ("locked decisions", "decisions", "invariants", "non-negotiable")))
    out_of_scope = bullets(section_text(sections, ("out of scope", "non-goals", "excluded")))
    authority = bullets(section_text(sections, ("human authority", "human gates", "approval", "authority")))
    return {
        "goal": goal or "UNRESOLVED — source plan does not expose a clear goal section.",
        "locked_decisions": locked,
        "out_of_scope": out_of_scope,
        "authority": authority,
        "source": source_master.name,
    }


def wayfinder_retrofit_artifacts(
    *,
    track: Path,
    source_master: Path | None,
    contracts: list[dict[str, Any]],
    ready: list[str],
    active: list[str],
    complete: list[str],
    blocked: list[dict[str, Any]],
    warnings: list[str],
) -> tuple[str, dict[str, Any]]:
    recovered = recovered_master_fields(source_master)
    trackers = [item["id"] for item in contracts if item.get("execution_policy") == "aggregate-only"]
    inferred = [item["id"] for item in contracts if item.get("migration", {}).get("requires_human_review")]
    fog = list(dict.fromkeys([
        *warnings,
        "Confirm every inferred dependency, risk lane, write set, conflict key, and tracker boundary before autonomous execution.",
        "Recover any authority gate or completion rule that is implicit rather than explicit in the preserved source plan.",
    ]))

    def md_list(values: list[str], empty: str = "None recovered from source; review required.") -> str:
        return "\n".join(f"- {value}" for value in values) if values else f"- {empty}"

    blocked_lines = [
        f"`{item['id']}` — blockers: {', '.join(item['remaining_blockers']) or item['source_status']}"
        for item in blocked
    ]
    map_text = f"""# Wayfinder Retrofit Map — {track.name}

## Purpose

This is a source-grounded migration map. It recovers the current route from preserved master-plan, ticket, validation, and status evidence; it does not silently redesign the product.

## Destination recovered from source

{recovered['goal']}

## Source authority

- Preserved master plan: `{recovered['source'] or 'UNRESOLVED'}`
- Preserved ticket and validation files under `{track.name}/`
- Explicit current human instructions outrank generated inferences.
- Generated contracts, lanes, and frontiers remain provisional until reviewed.

## Locked decisions recovered

{md_list(recovered['locked_decisions'])}

## Human authority gates recovered

{md_list(recovered['authority'])}

## Out of scope recovered

{md_list(recovered['out_of_scope'])}

## Current implementation position

- Tickets discovered: {len(contracts)}
- Ready implementation tickets: {', '.join(ready) or 'None'}
- Active tickets: {', '.join(active) or 'None'}
- Blocked tickets: {', '.join(blocked_lines) or 'None'}
- Complete tickets: {len(complete)}
- Aggregate-only trackers: {', '.join(trackers) or 'None'}
- Contracts requiring human review: {len(inferred)}

## Current planning frontier

1. Confirm the recovered destination and source-authority ordering.
2. Confirm inferred dependency edges and aggregate-only tracker boundaries.
3. Confirm risk lanes, authority gates, expected write sets, and semantic conflict keys.
4. Approve the generated verification, architecture, process, and model-routing policies.
5. Once those decisions are stable, run `execute-frontier` continuously from the local track.

## Fog and unresolved migration decisions

{md_list(fog, 'No warnings were detected, but generated inferences still require review.')}

## Exit criteria

- [ ] Destination and completion contract are confirmed.
- [ ] Dependency graph and tracker boundaries are confirmed.
- [ ] Risk lanes, human gates, write sets, and conflict keys are confirmed.
- [ ] Generated policies are approved or amended.
- [ ] `frontier.json` validates and at least one implementation ticket is safely selectable.
"""
    frontier_yaml = {
        "schema_version": 1,
        "effort": f"{track.name}-retrofit",
        "source_track": track.name,
        "items": [
            {"id": "D001", "title": "Confirm recovered destination and source authority", "type": "human-decision", "status": "ready", "blocked_by": [], "artifact": "decisions/D001-confirm-destination.md"},
            {"id": "D002", "title": "Confirm dependency graph and tracker boundaries", "type": "review", "status": "blocked", "blocked_by": ["D001"], "artifact": "decisions/D002-confirm-graph.md"},
            {"id": "D003", "title": "Confirm risk lanes, authority gates, and conflict domains", "type": "review", "status": "blocked", "blocked_by": ["D001", "D002"], "artifact": "decisions/D003-confirm-risk-and-authority.md"},
            {"id": "D004", "title": "Approve generated execution policies", "type": "human-decision", "status": "blocked", "blocked_by": ["D003"], "artifact": "decisions/D004-approve-policies.md"},
        ],
        "fog": fog,
        "implementation_frontier": {
            "ready": ready,
            "active": active,
            "blocked": [item["id"] for item in blocked],
            "complete": complete,
        },
        "generated_from_preserved_sources": True,
        "requires_human_review": True,
    }
    return map_text, frontier_yaml

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("track", type=Path, help="Existing ticket-track directory")
    parser.add_argument("--apply", action="store_true", help="Write additive generated files; default is dry-run")
    parser.add_argument("--force-generated", action="store_true", help="Replace only files previously generated by this tool")
    parser.add_argument("--flatten-ids", action="store_true", help="Assign flat T001-style contract IDs while retaining legacy IDs")
    parser.add_argument("--id-prefix", default="T", help="Prefix used with --flatten-ids (default: T)")
    parser.add_argument("--no-wayfinder", action="store_true", help="Do not generate the source-grounded Wayfinder retrofit map")
    parser.add_argument("--current-ticket", help="Explicit current ticket ID or directory name; overrides inferred journal status")
    parser.add_argument(
        "--current-status",
        choices=("ready", "in_progress", "review", "repair", "passed"),
        default="in_progress",
        help="Status assigned to --current-ticket (default: in_progress)",
    )
    parser.add_argument(
        "--trust-current-dependencies",
        action="store_true",
        help="Explicitly mark the current ticket's transitive blockers closed; use only when the stated current position proves they passed",
    )
    parser.add_argument("--status-overrides", type=Path, help="YAML/JSON mapping of legacy or canonical ticket IDs to statuses")
    args = parser.parse_args()

    track = args.track.resolve()
    if not track.is_dir():
        raise SystemExit(f"not a directory: {track}")

    sources = discover_tickets(track)
    if not sources:
        raise SystemExit(f"no ticket.md files found under {track}")
    make_ids(sources, args.flatten_ids, args.id_prefix)
    parent_map = infer_parents(sources)
    alias_map = build_alias_map(sources, track)

    actions: list[str] = []
    warnings: list[str] = []
    current_ticket_id = apply_status_evidence(
        track=track,
        sources=sources,
        alias_map=alias_map,
        current_ticket=args.current_ticket,
        current_status=args.current_status,
        trust_current_dependencies=args.trust_current_dependencies,
        status_overrides_path=args.status_overrides.resolve() if args.status_overrides else None,
        warnings=warnings,
    )
    contracts: list[dict[str, Any]] = []

    for source in sources:
        dependencies, unresolved = resolve_dependencies(source, alias_map, sources)
        contract = contract_for(source, track, dependencies, parent_map[source.canonical_id])
        contracts.append(contract)
        if unresolved:
            warnings.append(f"{source.canonical_id}: unresolved dependency tokens {sorted(set(unresolved))}")
        if source.validation_path is None:
            warnings.append(f"{source.canonical_id}: no validation.md or verification.md")
        if len(source.source_id.split("-")) > 4:
            warnings.append(
                f"{source.canonical_id}: deeply encoded legacy ID {source.source_id}; retain as an alias and use flat IDs for future tickets"
            )

    # A source tracker may claim completion while a nested child remains incomplete.
    # Generated scheduling state must fail closed: propagate incomplete aggregate children
    # upward before writing contracts or computing the execution frontier.
    by_contract_id = {contract["id"]: contract for contract in contracts}
    changed = True
    while changed:
        changed = False
        for contract in contracts:
            if contract["execution_policy"] != "aggregate-only" or contract["status"] not in DONE:
                continue
            incomplete = [
                dependency
                for dependency in contract["blocked_by"]
                if dependency in by_contract_id and by_contract_id[dependency]["status"] not in DONE
            ]
            if not incomplete:
                continue
            previous = contract["status"]
            contract["status"] = "blocked"
            retrofit = contract.setdefault("retrofit", {})
            retrofit["source_status_before_aggregate_reconciliation"] = previous
            retrofit["status_reason"] = (
                "aggregate completion was downgraded because declared child tickets remain incomplete: "
                + ", ".join(incomplete)
            )
            warnings.append(
                f"{contract['id']}: aggregate source status {previous!r} downgraded to blocked; incomplete children {incomplete}"
            )
            changed = True

    evidence_readme = """# Ticket Evidence

Evidence is append-only by attempt. Do not overwrite failed reviews or prior verification.

Recommended shape:

```text
evidence/
  attempts/001/
    implementation.json
    verification.json
    processes.json
    review-spec.json
    review-code.json
    review-ops.json
  result.json
```
"""
    for source, contract in zip(sources, contracts, strict=True):
        write_generated(
            source.directory / "contract.yaml",
            yaml.safe_dump(contract, sort_keys=False, allow_unicode=True),
            apply=args.apply,
            force=args.force_generated,
            actions=actions,
        )
        write_generated(
            source.directory / "evidence" / "README.md",
            evidence_readme,
            apply=args.apply,
            force=args.force_generated,
            actions=actions,
        )

    source_master = next((path for path in (track / "master-plan.md", track / "master-prompt.md") if path.exists()), None)
    if not (track / "master-plan.md").exists():
        body = f"""# {track.name} Frontier Loop Master Plan

## Source authority

The preserved source plan is `{source_master.name if source_master else 'UNRESOLVED'}`. This wrapper adds execution policy without rewriting product semantics.

## Frontier execution policy

Run `execute-frontier` continuously from this local folder. Keep the current conversation as coordinator, use one writer by default, parallelize read-only preflight and independent review, and serially land passed work. No GitHub issue, webhook, event watcher, or external scheduler is required.

## Human gates

UNRESOLVED — derive only from preserved source authority and explicit human decisions.

## Completion rule

Every required implementation ticket is passed and serially landed; tracker tickets aggregate child evidence; architecture budgets and process postconditions pass.
"""
        write_generated(track / "master-plan.md", body, apply=args.apply, force=args.force_generated, actions=actions)

    track_manifest = {
        "schema_version": 1,
        "track": track.name,
        "title": track.name.replace("-", " ").title(),
        "execution_mode": "frontier",
        "continuous_local_coordinator": True,
        "landing_policy": "serial",
        "default_writer_limit": 1,
        "max_writer_limit": 2,
        "source_master": source_master.name if source_master else None,
        "ids_flattened": args.flatten_ids,
        "current_ticket": current_ticket_id,
        "tickets": [
            {
                "id": contract["id"],
                "legacy_ids": contract["legacy_ids"],
                "kind": contract["kind"],
                "path": source.directory.relative_to(track).as_posix(),
            }
            for source, contract in zip(sources, contracts, strict=True)
        ],
    }
    write_generated(
        track / "track.yaml",
        yaml.safe_dump(track_manifest, sort_keys=False, allow_unicode=True),
        apply=args.apply,
        force=args.force_generated,
        actions=actions,
    )

    policies = {
        "verification.yaml": {
            "schema_version": 1,
            "red_green": ["L1"],
            "implementer_handoff": ["L0", "L1", "L2"],
            "integration_wave": ["L3"],
            "lane_3_landing": ["L0", "L1", "L2", "L3", "L4"],
        },
        "architecture-budgets.yaml": {
            "schema_version": 1,
            "file_defaults": {
                "test_warn_loc": 500,
                "test_split_plan_loc": 1000,
                "test_block_growth_loc": 1500,
                "new_test_file_hard_limit_loc": 2000,
                "production_warn_loc": 800,
                "production_split_plan_loc": 1500,
            },
            "patch_defaults": {
                "added_test_loc_to_locked_file": 0,
                "require_new_test_module_added_loc": 250,
            },
            "concentration": {"warn_top_10_share": 0.40},
            "locked_files": {},
            "test_globs": [
                "**/test_*.py", "**/*_test.py", "**/*.test.ts", "**/*.test.tsx",
                "**/*.spec.ts", "**/*.spec.tsx", "**/tests/**/*.rs", "**/*_tests.rs",
                "**/*_test.go", "**/*Test.java",
            ],
            "ignore_globs": [
                "**/.git/**", "**/.hg/**", "**/.svn/**", "**/node_modules/**",
                "**/target/**", "**/dist/**", "**/build/**", "**/.venv/**",
                "**/venv/**", "**/__pycache__/**",
            ],
        },
        "process.yaml": {
            "schema_version": 1,
            "lease_dir": ".agent/leases",
            "zero_owned_processes": True,
            "max_subagents": 3,
            "max_write_agents": 1,
        },
        "model-routing.yaml": {
            "schema_version": 1,
            "orchestrator": {"preferred": "gpt-5.6-sol", "effort": "high"},
            "planner": {"preferred": "gpt-5.6-sol", "effort": "high"},
            "scout": {"preferred": "gpt-5.3-codex", "effort": "high"},
            "implementer": {"preferred": "gpt-5.3-codex", "effort": "high"},
            "reviewer": {"preferred": "gpt-5.3-codex", "effort": "high"},
            "repairer": {"preferred": "gpt-5.3-codex", "effort": "high"},
            "integrator": {"preferred": "gpt-5.3-codex", "effort": "high"},
        },
    }
    for name, data in policies.items():
        write_generated(
            track / "policies" / name,
            yaml.safe_dump(data, sort_keys=False, allow_unicode=True),
            apply=args.apply,
            force=args.force_generated,
            actions=actions,
        )

    statuses = {contract["id"]: contract["status"] for contract in contracts}
    ready: list[str] = []
    aggregate_ready: list[str] = []
    active: list[str] = []
    blocked: list[dict[str, Any]] = []
    complete: list[str] = []
    for contract in contracts:
        ticket_id = contract["id"]
        status = contract["status"]
        aggregate = contract["execution_policy"] == "aggregate-only"
        if status in DONE:
            complete.append(ticket_id)
            continue
        if status in {"claimed", "in_progress", "review", "repair", "passed"}:
            active.append(ticket_id)
            continue
        remaining = [dependency for dependency in contract["blocked_by"] if statuses.get(dependency) not in DONE]
        if status == "blocked" or remaining:
            blocked.append(
                {
                    "id": ticket_id,
                    "remaining_blockers": remaining,
                    "source_status": status,
                    "aggregate_only": aggregate,
                }
            )
        elif status == "ready" and aggregate:
            aggregate_ready.append(ticket_id)
        elif status == "ready":
            ready.append(ticket_id)

    frontier = {
        "schema_version": 1,
        "track": track.name,
        "ready": ready,
        "aggregate_ready": aggregate_ready,
        "active": active,
        "blocked": blocked,
        "complete": complete,
        "generated_from_inferred_contracts": True,
    }
    write_generated_json(
        track / "frontier.json",
        frontier,
        apply=args.apply,
        force=args.force_generated,
        actions=actions,
    )

    sprint = """# Current Sprint

This file is the human-readable view of `frontier.json`. Regenerate or update it only after contract/status review.

## Ready for implementation

{ready}

## Ready for aggregation

{aggregate_ready}

## Active

{active}

## Blocked

{blocked}

## Complete

{complete}
""".format(
        ready="\n".join(f"- `{value}`" for value in ready) or "- None",
        aggregate_ready="\n".join(f"- `{value}`" for value in aggregate_ready) or "- None",
        active="\n".join(f"- `{value}`" for value in active) or "- None",
        blocked="\n".join(f"- `{value['id']}` — blockers: {', '.join(value['remaining_blockers']) or value['source_status']}" for value in blocked) or "- None",
        complete="\n".join(f"- `{value}`" for value in complete) or "- None",
    )
    write_generated(track / "current-sprint.md", sprint, apply=args.apply, force=args.force_generated, actions=actions)

    wayfinder_paths: list[str] = []
    if not args.no_wayfinder:
        map_text, planning_frontier = wayfinder_retrofit_artifacts(
            track=track,
            source_master=source_master,
            contracts=contracts,
            ready=ready,
            active=active,
            complete=complete,
            blocked=blocked,
            warnings=warnings,
        )
        track_map = track / "wayfinder-retrofit.md"
        write_generated(track_map, map_text, apply=args.apply, force=args.force_generated, actions=actions)
        write_generated(
            track / "wayfinder-frontier.yaml",
            yaml.safe_dump(planning_frontier, sort_keys=False, allow_unicode=True),
            apply=args.apply,
            force=args.force_generated,
            actions=actions,
        )
        wayfinder_paths.extend([str(track_map), str(track / "wayfinder-frontier.yaml")])

        docs_root = infer_docs_root(track)
        if docs_root is not None:
            effort = docs_root / "agent" / "wayfinding" / f"{track.name}-retrofit"
            write_generated(effort / "map.md", map_text, apply=args.apply, force=args.force_generated, actions=actions)
            write_generated(
                effort / "frontier.yaml",
                yaml.safe_dump(planning_frontier, sort_keys=False, allow_unicode=True),
                apply=args.apply,
                force=args.force_generated,
                actions=actions,
            )
            decisions_readme = """# Recovered decisions\n\nCreate one file per confirmed migration decision. Do not convert generated inference into a locked product decision without human review.\n"""
            write_generated(effort / "decisions" / "README.md", decisions_readme, apply=args.apply, force=args.force_generated, actions=actions)
            wayfinder_paths.extend([str(effort / "map.md"), str(effort / "frontier.yaml")])

    report_lines = [
        f"# Ticket Pack Retrofit Report — {track.name}",
        "",
        f"Date: {date.today().isoformat()}",
        "",
        f"Tickets discovered: {len(contracts)}",
        f"Contract IDs flattened: {'yes' if args.flatten_ids else 'no'}",
        f"Wayfinder migration artifacts: {'disabled' if args.no_wayfinder else 'generated/planned'}",
        "",
        "## Safety statement",
        "",
        "Original ticket and validation files were not rewritten. All inferred fields require human review before autonomous execution.",
        "",
        "## Warnings",
        "",
        *([f"- {warning}" for warning in warnings] or ["- None."]),
        "",
        "## Planned/generated actions",
        "",
        *[f"- {action}" for action in actions],
    ]
    write_generated(
        track / "retrofit-report.md",
        "\n".join(report_lines),
        apply=args.apply,
        force=args.force_generated,
        actions=actions,
    )

    print(
        json.dumps(
            {
                "track": str(track),
                "apply": args.apply,
                "tickets": len(contracts),
                "ids_flattened": args.flatten_ids,
                "current_ticket": current_ticket_id,
                "wayfinder_artifacts": wayfinder_paths,
                "warnings": warnings,
                "actions": actions,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
