import { DEPENDENCY_SNAPSHOT } from "../constants.js";

export function asJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

export function biomeConfig() {
  return asJson({
    $schema: `https://biomejs.dev/schemas/${DEPENDENCY_SNAPSHOT.biome}/schema.json`,
    formatter: {
      enabled: true,
      indentStyle: "space",
      lineWidth: 100,
    },
    linter: {
      enabled: true,
    },
    javascript: {
      formatter: {
        quoteStyle: "double",
        semicolons: "always",
      },
    },
  });
}

export function nodeGitignore() {
  return `node_modules/
dist/
coverage/
.env
.env.*
!.env.example
.DS_Store
`;
}

export function packageManagerLockHint(packageManager) {
  return {
    npm: "package-lock.json",
    pnpm: "pnpm-lock.yaml",
    yarn: "yarn.lock",
    bun: "bun.lock",
  }[packageManager];
}

export function generatedReadme({
  projectName,
  project,
  style,
  tdd,
  commands,
  structure,
  notes = [],
}) {
  const noteBlock = notes.length
    ? `\n## Stack notes\n\n${notes.map((note) => `- ${note}`).join("\n")}\n`
    : "";

  return `# ${projectName}

Agent-ready **${project}** starter generated by \`workspace-template\`.

## Profile

- Implementation style: \`${style}\`
- TDD mode: \`${tdd}\`
- Stable agent context: \`AGENTS.md\`
- Machine-readable architecture policy: \`.agentic/profile.json\`
- Canonical local skills: \`.agentic/skills/\`

## Start

\`\`\`bash
${commands.setup}
${commands.dev}
\`\`\`

## Quality loop

\`\`\`bash
${commands.test}
${commands.typecheck}
${commands.lint}
${commands.full}
\`\`\`

## Example structure

\`\`\`text
${structure}
\`\`\`

The sample is intentionally small. Keep feature code together, move effects to explicit boundaries, and add layers only when they protect a real change pressure.
${noteBlock}
## Agent skill maintenance

Edit the canonical skills under \`.agentic/skills/\`, then refresh harness-specific copies:

\`\`\`bash
npx workspace-template sync .
npx workspace-template doctor .
\`\`\`
`;
}
