export { adoptProject, applyAdoptionPlan } from "./adopt.js";
export { buildAdoptionPlan } from "./adoption-plan.js";
export { parseArgs } from "./args.js";
export { createProject } from "./create.js";
export { doctorProject, validateSkillTree } from "./doctor.js";
export { inspectRepository } from "./inspection.js";
export { syncSkills } from "./sync.js";
export { discoverWorkspace } from "./workspace/discover.js";
export { verifyWorkspace } from "./workspace/verify.js";
export * from "./plans/index.js";
export * from "./tooling/index.js";
export * from "./skills/index.js";
export * from "./restructure/index.js";
export * from "./align/index.js";
export * from "./presets/index.js";
export * from "./upgrade/index.js";
